[update]
tasks = ["code", "normalize"]

[update.code]
codePath = "../DashSync/"
localizablePath = "../DashSync/"
defaultToKeys = false
customFunction = "DSLocalizedString"
additive = true
unstripped = false

[update.normalize]
path = "."
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "."
duplicateKeys = true
emptyValues = true
