name: Continuous Integration

on:
  push:
    branches:
      - master
      - develop
      - nightly
      - fix/CI
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Install automake
        run: |
          brew install automake
      - name: Checkout DashSync
        uses: actions/checkout@v2
        with:
          path: dashsync
          submodules: recursive
      - name: Create LFS file list
        run: |
          git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
        working-directory: ./dashsync
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: dashsync/.git/lfs
          key: lfs-${{ hashFiles('.lfs-assets-id') }}-v1
      - name: Git LFS Pull
        run: git lfs pull
        working-directory: ./dashsync
      - uses: actions/cache@v2
        with:
          path: ./dashsync/Example/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Check cocoapods
		run: ./dashsync/Example/check_cocoapods.sh
		shell: bash
      - name: Dependencies
        working-directory: ./dashsync/Example
        run: pod install
      - name: Build
        working-directory: ./dashsync/Example
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild build -scheme "DashSync-Example" -workspace "DashSync.xcworkspace" -destination "platform=$platform,name=iPhone 13"
