name: Continuous Integration

on:
  push:
    branches:
      - master
      - develop
      - nightly
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build and Test using iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout DashSync
        uses: actions/checkout@v2
        with:
          path: dashsync
      - uses: Checkout DashGRPC
        with:
          path: dapi-grpc
          repository: 'dashevo/dapi-grpc'
          ref: 'v0.16.0-dev.3'
      - uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Example/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Build
        working-directory: ./Example
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=`instruments -s -devices | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
          xcodebuild build-for-testing -scheme "DashSync-Example" -workspace "DashSync.xcworkspace" -destination "platform=$platform,name=$device"
      - name: Test
        working-directory: ./Example
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=`instruments -s -devices | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
          xcodebuild test-without-building -scheme "DashSync-Example" -workspace "DashSync.xcworkspace"  -destination "platform=$platform,name=$device"
