name: E2E Tests

on:
  push:
    branches:
      - master
      - develop
      - nightly
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Testnet E2E Tests
    runs-on: macOS-latest
    steps:
      - name: Install automake
        run: |
          brew install automake
      - name: Checkout DashSync
        uses: actions/checkout@v2
        with:
          path: dashsync
          submodules: recursive
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
        working-directory: ./dashsync
      - uses: actions/cache@v2
        with:
          path: ./dashsync/Example/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Dependencies
        working-directory: ./dashsync/Example
        run: pod install
      - name: Build
        working-directory: ./dashsync/Example
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild build-for-testing -scheme "DashSync-Example" -workspace "DashSync.xcworkspace" -destination "platform=$platform,name=iPhone 13"
      - name: Test Syncing Chain
        working-directory: ./dashsync/Example
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild test-without-building -scheme "DashSync-Example" -workspace "DashSync.xcworkspace"  -destination "platform=$platform,name=iPhone 13" -testPlan TestnetE2ETests
