name: Lint

on:
  push:
    branches:
      - master
      - develop
      - nightly
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Objective-C Linter
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: OCLint
        run: |
          brew tap oclint/formulae
          brew install oclint
      - name: Dependencies
        run: pod install
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
      - name: Lint
        working-directory: ./Example
        run: |
          sh run_oclint.sh

