name: Lint

on:
  push:
    branches:
      - master
      - develop
      - nightly
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Objective-C Linter
    runs-on: macOS-latest
    steps:
      - name: Checkout DashSync
        uses: actions/checkout@v2
        with:
          path: dashsync
      - name: Checkout DashGRPC
        uses: actions/checkout@v2
        with:
          path: dapi-grpc
          repository: 'dashevo/dapi-grpc'
          ref: 'v0.16.0-dev.3'
      - name: OCLint
        run: |
          brew tap oclint/formulae
          brew install oclint
      - name: Dependencies
        working-directory: ./Example
        run: pod install
      - name: Lint
        working-directory: ./Example
        run: |
          sh run_oclint.sh

