name: Network

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Check Network
    runs-on: macOS-latest
    steps:
      - name: Checkout DashSync
        uses: actions/checkout@v2
        with:
          path: dashsync
      - name: Checkout DashGRPC
        uses: actions/checkout@v2
        with:
          path: dapi-grpc
          repository: 'dashevo/dapi-grpc'
          ref: 'v0.16.0-dev.3'
      - uses: actions/cache@v2
        with:
          path: ./dashsync/Example/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Dependencies
        working-directory: ./dashsync/Example
        run: pod install
      - name: Build
        working-directory: ./dashsync/Example
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=`instruments -s -devices | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
          xcodebuild build -scheme "NetworkInfo" -workspace "DashSync.xcworkspace" -destination "platform=$platform,name=$device"
      - name: Get Network Info and Ping Nodes
        working-directory: ./dashsync/Example
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=`instruments -s -devices | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
          xcodebuild test-without-building -scheme "NetworkInfo" -workspace "DashSync.xcworkspace"  -destination "platform=$platform,name=$device"
      - name: Archive network ping results
        uses: actions/upload-artifact@v2
        with:
          name: testnet-network-report
          path: output/test/testnet-network.json
